---
- hosts: localhost
  vars:
    ansi_dir: "/home/docker/.ansible"
    ansi_user: docker
    ansi_group: docker
  tasks:

  - name: ansible-setup.yml --- create ansible directory structure
    ansible.builtin.file:
      path: "{{ ansi_dir}}/{{ item }}"
      state: directory
      owner: "{{ ansi_user }}"
      group: "{{ ansi_group }}"
      mode: '0755'
    with_items:
      - facts
      - files
      - inventory
      - inventory/group_vars
      - inventory/host_vars
      - playbooks
      - roles
