name: image build and push

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - LICENSE
      - Dockerfiles/.template
      - .gitignore
  repository_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build container
      run: "docker build --no-cache -f Dockerfiles/base.Dockerfile -t ${GITHUB_REPOSITORY}:baseimage ."

    - name: Login to docker hub
      run: "echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin"

    - name: Push to registry
      run:  "docker push ${GITHUB_REPOSITORY}:baseimage"

  trigger_docker_repo_dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["ansible"] # Branch names
    steps:
      - name: Dispatch initiating repository event
        run: |
          curl -XPOST \
          -u ${{ secrets.ACCESS_TOKEN }} \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/dovry/docker_${{ matrix.branch }}/dispatches \
          --data '{"event_type": "build_application"}'