name: image build and push
# DO NOT COMMIT THIS FILE TO MASTER
on: 
  push:
    branches:
      - master
      - ansible
    paths-ignore:
      - 'README.md'
      - LICENSE
      - Dockerfiles/.template
      - .gitignore
  repository_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    env:
      branch: ansible # CHANGE THIS
    steps:
    - uses: actions/checkout@v1
      
    - name: echo var
      run: "echo ${GITHUB_BRANCH_NAME}"

    - name: Build container
      run: "docker build --no-cache -f Dockerfiles/${branch}.Dockerfile -t ${GITHUB_REPOSITORY}:${branch} ."

    - name: Login to docker hub
      run: "echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin"

    - name: Push to registry
      run:  "docker push ${GITHUB_REPOSITORY}:${branch}"
